import type { Metadata } from "next";
import { CheckCircle2 } from "lucide-react";
import { Container } from "@/components/Container";
import { PartnerRequestForm } from "@/components/PartnerRequestForm";

export const metadata: Metadata = { title: "Dla partnerów", description: "Zgłoś ofertę i rozwijaj współpracę z Dealshare." };
const benefits = ["Lepiej przygotowane leady", "Mniej przypadkowych zapytań", "Jasny kontekst sprawy", "Statusy i historia kontaktu", "Podstawa do rozliczania współpracy", "Widoczność dla właściwych firm"];
const model = [["Dla kogo jest współpraca","Dla firm z konkretną, możliwą do zweryfikowania ofertą B2B i gotowością do pracy w uporządkowanym procesie."],["Jak działa zgłoszenie oferty","Opisujesz ofertę i grupę klientów. Dealshare weryfikuje zakres, jakość i sposób prezentacji przed publikacją."],["Co dostaje partner","Sprawy z kontekstem, czytelny status i dostęp tylko do danych potrzebnych przy konkretnym przypisaniu."],["Jak wygląda panel oferenta","Po akceptacji dodatkowe zakładki pojawiają się w tym samym koncie i panelu Dealshare."],["Jak dbamy o jakość","Dealshare zatwierdza partnerów i oferty, kontroluje widoczność oraz może wstrzymać publikację."]];
export default function PartnersPage(){return <main><section className="bg-navy py-16 text-white"><Container><p className="text-sm font-black uppercase tracking-[0.18em] text-cyan">Dla partnerów</p><h1 className="mt-4 max-w-5xl text-4xl font-black sm:text-6xl">Masz ofertę dla przedsiębiorców? Pokaż ją właściwym firmom przez Dealshare.</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-white/75">Dealshare pomaga partnerom prezentować oferty, zbierać lepiej przygotowane zgłoszenia i prowadzić sprawy w uporządkowanym procesie.</p></Container></section><section className="bg-white py-14 sm:py-20"><Container><div className="grid gap-10 lg:grid-cols-[0.85fr_1.15fr]"><div><p className="text-sm font-black uppercase tracking-[0.18em] text-teal">Model współpracy</p><h2 className="mt-3 text-3xl font-black text-navy">Selektywnie, nie masowo</h2><p className="mt-4 text-sm leading-7 text-slate-600">Partnerzy działają po akceptacji Dealshare. Nie każdy może automatycznie publikować oferty, a każda nowa oferta wymaga zatwierdzenia.</p><ul className="mt-6 grid gap-3">{benefits.map(item=><li key={item} className="flex items-center gap-3 text-sm font-bold text-navy"><CheckCircle2 size={18} className="text-teal" />{item}</li>)}</ul></div><div className="divide-y divide-slate-200 border-y border-slate-200">{model.map(([title,text])=><article key={title} className="py-5"><h3 className="font-black text-navy">{title}</h3><p className="mt-2 text-sm leading-7 text-slate-600">{text}</p></article>)}</div></div></Container></section><section id="zglos-oferte" className="bg-mist py-14 sm:py-20"><Container className="max-w-4xl"><p className="text-sm font-black uppercase tracking-[0.18em] text-teal">Zgłoś ofertę</p><h2 className="mt-3 text-3xl font-black text-navy">Rozszerz konto do oferenta</h2><p className="mt-4 mb-8 max-w-2xl text-sm leading-7 text-slate-600">Zgłoszenie otrzyma status oczekujący. Funkcje oferenta pojawią się w panelu dopiero po akceptacji Dealshare.</p><PartnerRequestForm /></Container></section></main>}
