import type { Metadata } from "next";
import { CheckCircle2 } from "lucide-react";
import { Container } from "@/components/Container";
import { PartnerRequestForm } from "@/components/PartnerRequestForm";

export const metadata: Metadata = { title: "Dla partnerów", description: "Zgłoś ofertę i rozwijaj współpracę z Dealshare." };
const benefits = ["Lepiej przygotowane rozmowy", "Mniej przypadkowych zapytań", "Jasny kontekst każdej potrzeby", "Czytelna historia kontaktu", "Przejrzyste zasady współpracy", "Dotarcie do właściwych firm"];
const model = [["Dla kogo jest współpraca","Dla firm z konkretną, możliwą do zweryfikowania ofertą B2B i gotowością do rzetelnej obsługi przedsiębiorców."],["Jak zaczynamy","Opisujesz ofertę i firmy, którym może pomóc. Poznajemy jej zakres, jakość oraz sposób prezentacji."],["Co zyskujesz","Kontakt z firmami, których potrzeby pasują do Twojej oferty, wraz z kontekstem potrzebnym do dobrej rozmowy."],["Wszystko w jednym koncie","Po rozpoczęciu współpracy w swoim koncie zobaczysz oferty oraz przekazane przez Dealshare zapytania."],["Jak dbamy o jakość","Każdą firmę i propozycję poznajemy przed publikacją. Możemy też poprosić o uzupełnienia lub wstrzymać prezentację oferty."]];
export default function PartnersPage(){return <main><section className="bg-navy py-16 text-white"><Container><p className="text-sm font-black uppercase tracking-[0.18em] text-cyan">Współpraca z Dealshare</p><h1 className="mt-4 max-w-5xl text-4xl font-black sm:text-6xl">Masz wartościową ofertę dla firm? Pomóżmy jej dotrzeć we właściwe miejsce.</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-white/75">Łączymy sprawdzone propozycje z przedsiębiorcami, którzy naprawdę mogą z nich skorzystać. Bez przypadkowych kontaktów i masowej publikacji.</p></Container></section><section className="bg-white py-14 sm:py-20"><Container><div className="grid gap-10 lg:grid-cols-[0.85fr_1.15fr]"><div><p className="text-sm font-black uppercase tracking-[0.18em] text-teal">Zasady współpracy</p><h2 className="mt-3 text-3xl font-black text-navy">Liczy się jakość i dobre dopasowanie</h2><p className="mt-4 text-sm leading-7 text-slate-600">Zanim pokażemy ofertę przedsiębiorcom, chcemy dobrze poznać jej wartość, zakres i sposób realizacji.</p><ul className="mt-6 grid gap-3">{benefits.map(item=><li key={item} className="flex items-center gap-3 text-sm font-bold text-navy"><CheckCircle2 size={18} className="text-teal" />{item}</li>)}</ul></div><div className="divide-y divide-slate-200 border-y border-slate-200">{model.map(([title,text])=><article key={title} className="py-5"><h3 className="font-black text-navy">{title}</h3><p className="mt-2 text-sm leading-7 text-slate-600">{text}</p></article>)}</div></div></Container></section><section id="zglos-oferte" className="bg-mist py-14 sm:py-20"><Container className="max-w-4xl"><p className="text-sm font-black uppercase tracking-[0.18em] text-teal">Przedstaw swoją ofertę</p><h2 className="mt-3 text-3xl font-black text-navy">Zacznij rozmowę o współpracy</h2><p className="mt-4 mb-8 max-w-2xl text-sm leading-7 text-slate-600">Opowiedz nam, co oferujesz i komu możesz pomóc. Po zapoznaniu się z informacjami skontaktujemy się w sprawie kolejnych kroków.</p><PartnerRequestForm /></Container></section></main>}
