import Link from "next/link";
import { asc, eq } from "drizzle-orm";
import { db } from "@/db/client";
import { cases, organizations, users } from "@/db/schema";
import { getAdminCaseStatus } from "@/lib/case-status";

const columns = [{title:"Nowe",statuses:["new"]},{title:"Analiza",statuses:["qualification"]},{title:"Do uzupełnienia",statuses:["needs_info"]},{title:"Dobór rozwiązania",statuses:["matching"]},{title:"Przekazane partnerowi",statuses:["partner_pending","partner_accepted","contact_preparation"]},{title:"Rozmowa / oferta",statuses:["meeting_or_offer"]},{title:"Finalizacja",statuses:["decision","activated","billing"]},{title:"Zamknięte",statuses:["closed_won","closed_lost"]}];

export default async function AdminCasesPage(){const rows=await db.select({id:cases.id,caseNumber:cases.caseNumber,title:cases.title,status:cases.status,pathType:cases.pathType,category:cases.category,createdAt:cases.createdAt,clientName:users.name,companyName:organizations.name}).from(cases).leftJoin(users,eq(cases.userId,users.id)).leftJoin(organizations,eq(cases.organizationId,organizations.id)).orderBy(asc(cases.createdAt));return <div><div className="mb-5"><p className="text-xs font-black uppercase tracking-[0.16em] text-teal">Przebieg obsługi</p><h2 className="mt-1 text-3xl font-black text-navy">Zgłoszenia</h2></div><div className="grid gap-3 overflow-x-auto pb-4 xl:grid-cols-4 2xl:grid-cols-8">{columns.map(column=>{const items=rows.filter(item=>column.statuses.includes(item.status));return <section key={column.title} className="min-w-[240px] rounded-md border border-slate-200 bg-slate-50"><header className="border-b border-slate-200 px-3 py-3"><h3 className="text-xs font-black uppercase text-navy">{column.title}</h3><p className="mt-1 text-xs text-slate-500">{items.length} zgłoszeń</p></header><div className="grid gap-2 p-2">{items.map(item=><Link key={item.id} href={`/admin/sprawy/${item.caseNumber}`} className="rounded border border-slate-200 bg-white p-3 shadow-sm hover:border-electric/30"><p className="font-mono text-xs font-black text-electric">{item.caseNumber}</p><h4 className="mt-2 text-sm font-black text-navy">{item.title}</h4><p className="mt-2 text-xs leading-5 text-slate-500">{item.companyName || item.clientName}<br/>{getAdminCaseStatus(item.status)}</p></Link>)}</div></section>})}</div></div>}
